Describe new function for string_fucntion_example
ricky-aug/Git_Pull_Request pull request #1
Opened 2018-01-30 09:54 UTC by tricharu

Please review it and let me know your feedback

2018-01-30 10:25 UTC, ricky-aug commented on string_function_examples.py
> +# upper() return the string in upper case
use multi line comment which is our coding standard

2018-01-30 13:36 UTC, ricky-aug requested changes

2018-01-30 13:36 UTC, ricky-aug commented on string_function_examples.py
> +print(s.isupper()) #False
Don't give the o/p it is not good

2018-01-31 05:17 UTC, tricharu commented on string_function_examples.py
> +'''
provide the multi line comment

2018-01-31 05:18 UTC, tricharu commented on string_function_examples.py
> +print(s.isupper()) #may be true or false depends on the string and return value of isupper()
Changed the comment regarding the true and false

2018-01-31 05:22 UTC, ricky-aug approved these changes

2018-01-31 05:23 UTC, merged